<?php
/**
 * District
 *
 * PHP version 5
 *
 * @category Class
 * @package  Clever\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Data API
 *
 * Serves the Clever Data API
 *
 * OpenAPI spec version: 3.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.27
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Clever\Client\Model;

use \ArrayAccess;
use \Clever\Client\ObjectSerializer;

/**
 * District Class Doc Comment
 *
 * @category Class
 * @package  Clever\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class District implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'District';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'string',
        'name' => 'string',
        'mdrNumber' => 'string',
        'ncesId' => 'string',
        'sisType' => 'string',
        'state' => 'string',
        'lastSync' => 'string',
        'error' => 'string',
        'pauseStart' => 'string',
        'pauseEnd' => 'string',
        'launchDate' => '\DateTime',
        'portalUrl' => 'string',
        'loginMethods' => 'string[]',
        'districtContact' => '\Clever\Client\Model\DistrictContact'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => null,
        'name' => null,
        'mdrNumber' => null,
        'ncesId' => null,
        'sisType' => null,
        'state' => null,
        'lastSync' => 'datetime',
        'error' => null,
        'pauseStart' => 'datetime',
        'pauseEnd' => 'datetime',
        'launchDate' => 'date',
        'portalUrl' => null,
        'loginMethods' => null,
        'districtContact' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'mdrNumber' => 'mdr_number',
        'ncesId' => 'nces_id',
        'sisType' => 'sis_type',
        'state' => 'state',
        'lastSync' => 'last_sync',
        'error' => 'error',
        'pauseStart' => 'pause_start',
        'pauseEnd' => 'pause_end',
        'launchDate' => 'launch_date',
        'portalUrl' => 'portal_url',
        'loginMethods' => 'login_methods',
        'districtContact' => 'district_contact'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'mdrNumber' => 'setMdrNumber',
        'ncesId' => 'setNcesId',
        'sisType' => 'setSisType',
        'state' => 'setState',
        'lastSync' => 'setLastSync',
        'error' => 'setError',
        'pauseStart' => 'setPauseStart',
        'pauseEnd' => 'setPauseEnd',
        'launchDate' => 'setLaunchDate',
        'portalUrl' => 'setPortalUrl',
        'loginMethods' => 'setLoginMethods',
        'districtContact' => 'setDistrictContact'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'mdrNumber' => 'getMdrNumber',
        'ncesId' => 'getNcesId',
        'sisType' => 'getSisType',
        'state' => 'getState',
        'lastSync' => 'getLastSync',
        'error' => 'getError',
        'pauseStart' => 'getPauseStart',
        'pauseEnd' => 'getPauseEnd',
        'launchDate' => 'getLaunchDate',
        'portalUrl' => 'getPortalUrl',
        'loginMethods' => 'getLoginMethods',
        'districtContact' => 'getDistrictContact'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const STATE_RUNNING = 'running';
    const STATE_PENDING = 'pending';
    const STATE_ERROR = 'error';
    const STATE_PAUSED = 'paused';
    const STATE_EMPTY = '';
    const STATE_SUCCESS = 'success';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStateAllowableValues()
    {
        return [
            self::STATE_RUNNING,
            self::STATE_PENDING,
            self::STATE_ERROR,
            self::STATE_PAUSED,
            self::STATE_EMPTY,
            self::STATE_SUCCESS,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['mdrNumber'] = isset($data['mdrNumber']) ? $data['mdrNumber'] : null;
        $this->container['ncesId'] = isset($data['ncesId']) ? $data['ncesId'] : null;
        $this->container['sisType'] = isset($data['sisType']) ? $data['sisType'] : null;
        $this->container['state'] = isset($data['state']) ? $data['state'] : null;
        $this->container['lastSync'] = isset($data['lastSync']) ? $data['lastSync'] : null;
        $this->container['error'] = isset($data['error']) ? $data['error'] : null;
        $this->container['pauseStart'] = isset($data['pauseStart']) ? $data['pauseStart'] : null;
        $this->container['pauseEnd'] = isset($data['pauseEnd']) ? $data['pauseEnd'] : null;
        $this->container['launchDate'] = isset($data['launchDate']) ? $data['launchDate'] : null;
        $this->container['portalUrl'] = isset($data['portalUrl']) ? $data['portalUrl'] : null;
        $this->container['loginMethods'] = isset($data['loginMethods']) ? $data['loginMethods'] : null;
        $this->container['districtContact'] = isset($data['districtContact']) ? $data['districtContact'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getStateAllowableValues();
        if (!is_null($this->container['state']) && !in_array($this->container['state'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'state', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets mdrNumber
     *
     * @return string
     */
    public function getMdrNumber()
    {
        return $this->container['mdrNumber'];
    }

    /**
     * Sets mdrNumber
     *
     * @param string $mdrNumber mdrNumber
     *
     * @return $this
     */
    public function setMdrNumber($mdrNumber)
    {
        $this->container['mdrNumber'] = $mdrNumber;

        return $this;
    }

    /**
     * Gets ncesId
     *
     * @return string
     */
    public function getNcesId()
    {
        return $this->container['ncesId'];
    }

    /**
     * Sets ncesId
     *
     * @param string $ncesId ncesId
     *
     * @return $this
     */
    public function setNcesId($ncesId)
    {
        $this->container['ncesId'] = $ncesId;

        return $this;
    }

    /**
     * Gets sisType
     *
     * @return string
     */
    public function getSisType()
    {
        return $this->container['sisType'];
    }

    /**
     * Sets sisType
     *
     * @param string $sisType sisType
     *
     * @return $this
     */
    public function setSisType($sisType)
    {
        $this->container['sisType'] = $sisType;

        return $this;
    }

    /**
     * Gets state
     *
     * @return string
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     *
     * @param string $state state
     *
     * @return $this
     */
    public function setState($state)
    {
        $allowedValues = $this->getStateAllowableValues();
        if (!is_null($state) && !in_array($state, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'state', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets lastSync
     *
     * @return string
     */
    public function getLastSync()
    {
        return $this->container['lastSync'];
    }

    /**
     * Sets lastSync
     *
     * @param string $lastSync lastSync
     *
     * @return $this
     */
    public function setLastSync($lastSync)
    {
        $this->container['lastSync'] = $lastSync;

        return $this;
    }

    /**
     * Gets error
     *
     * @return string
     */
    public function getError()
    {
        return $this->container['error'];
    }

    /**
     * Sets error
     *
     * @param string $error error
     *
     * @return $this
     */
    public function setError($error)
    {
        $this->container['error'] = $error;

        return $this;
    }

    /**
     * Gets pauseStart
     *
     * @return string
     */
    public function getPauseStart()
    {
        return $this->container['pauseStart'];
    }

    /**
     * Sets pauseStart
     *
     * @param string $pauseStart pauseStart
     *
     * @return $this
     */
    public function setPauseStart($pauseStart)
    {
        $this->container['pauseStart'] = $pauseStart;

        return $this;
    }

    /**
     * Gets pauseEnd
     *
     * @return string
     */
    public function getPauseEnd()
    {
        return $this->container['pauseEnd'];
    }

    /**
     * Sets pauseEnd
     *
     * @param string $pauseEnd pauseEnd
     *
     * @return $this
     */
    public function setPauseEnd($pauseEnd)
    {
        $this->container['pauseEnd'] = $pauseEnd;

        return $this;
    }

    /**
     * Gets launchDate
     *
     * @return \DateTime
     */
    public function getLaunchDate()
    {
        return $this->container['launchDate'];
    }

    /**
     * Sets launchDate
     *
     * @param \DateTime $launchDate launchDate
     *
     * @return $this
     */
    public function setLaunchDate($launchDate)
    {
        $this->container['launchDate'] = $launchDate;

        return $this;
    }

    /**
     * Gets portalUrl
     *
     * @return string
     */
    public function getPortalUrl()
    {
        return $this->container['portalUrl'];
    }

    /**
     * Sets portalUrl
     *
     * @param string $portalUrl portalUrl
     *
     * @return $this
     */
    public function setPortalUrl($portalUrl)
    {
        $this->container['portalUrl'] = $portalUrl;

        return $this;
    }

    /**
     * Gets loginMethods
     *
     * @return string[]
     */
    public function getLoginMethods()
    {
        return $this->container['loginMethods'];
    }

    /**
     * Sets loginMethods
     *
     * @param string[] $loginMethods loginMethods
     *
     * @return $this
     */
    public function setLoginMethods($loginMethods)
    {
        $this->container['loginMethods'] = $loginMethods;

        return $this;
    }

    /**
     * Gets districtContact
     *
     * @return \Clever\Client\Model\DistrictContact
     */
    public function getDistrictContact()
    {
        return $this->container['districtContact'];
    }

    /**
     * Sets districtContact
     *
     * @param \Clever\Client\Model\DistrictContact $districtContact districtContact
     *
     * @return $this
     */
    public function setDistrictContact($districtContact)
    {
        $this->container['districtContact'] = $districtContact;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


