<?php
/**
 * RolesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Clever\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Clever API
 *
 * The Clever API
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Clever\Client;

/**
 * RolesTest Class Doc Comment
 *
 * @category    Class
 * @description Roles
 * @package     Clever\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RolesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Roles"
     */
    public function testRoles()
    {
    }

    /**
     * Test attribute "contact"
     */
    public function testPropertyContact()
    {
    }

    /**
     * Test attribute "district_admin"
     */
    public function testPropertyDistrictAdmin()
    {
    }

    /**
     * Test attribute "staff"
     */
    public function testPropertyStaff()
    {
    }

    /**
     * Test attribute "student"
     */
    public function testPropertyStudent()
    {
    }

    /**
     * Test attribute "teacher"
     */
    public function testPropertyTeacher()
    {
    }
}
