<?php
/**
 * DataApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Clever API
 *
 * The Clever API
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * DataApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DataApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getContactsForUser
     *
     * .
     *
     */
    public function testGetContactsForUser()
    {
    }

    /**
     * Test case for getCourse
     *
     * .
     *
     */
    public function testGetCourse()
    {
    }

    /**
     * Test case for getCourseForSection
     *
     * .
     *
     */
    public function testGetCourseForSection()
    {
    }

    /**
     * Test case for getCourses
     *
     * .
     *
     */
    public function testGetCourses()
    {
    }

    /**
     * Test case for getCoursesForResource
     *
     * .
     *
     */
    public function testGetCoursesForResource()
    {
    }

    /**
     * Test case for getCoursesForSchool
     *
     * .
     *
     */
    public function testGetCoursesForSchool()
    {
    }

    /**
     * Test case for getDistrict
     *
     * .
     *
     */
    public function testGetDistrict()
    {
    }

    /**
     * Test case for getDistrictForCourse
     *
     * .
     *
     */
    public function testGetDistrictForCourse()
    {
    }

    /**
     * Test case for getDistrictForSchool
     *
     * .
     *
     */
    public function testGetDistrictForSchool()
    {
    }

    /**
     * Test case for getDistrictForSection
     *
     * .
     *
     */
    public function testGetDistrictForSection()
    {
    }

    /**
     * Test case for getDistrictForTerm
     *
     * .
     *
     */
    public function testGetDistrictForTerm()
    {
    }

    /**
     * Test case for getDistrictForUser
     *
     * .
     *
     */
    public function testGetDistrictForUser()
    {
    }

    /**
     * Test case for getDistricts
     *
     * .
     *
     */
    public function testGetDistricts()
    {
    }

    /**
     * Test case for getResource
     *
     * .
     *
     */
    public function testGetResource()
    {
    }

    /**
     * Test case for getResources
     *
     * .
     *
     */
    public function testGetResources()
    {
    }

    /**
     * Test case for getResourcesForCourse
     *
     * .
     *
     */
    public function testGetResourcesForCourse()
    {
    }

    /**
     * Test case for getResourcesForSection
     *
     * .
     *
     */
    public function testGetResourcesForSection()
    {
    }

    /**
     * Test case for getResourcesForUser
     *
     * .
     *
     */
    public function testGetResourcesForUser()
    {
    }

    /**
     * Test case for getSchool
     *
     * .
     *
     */
    public function testGetSchool()
    {
    }

    /**
     * Test case for getSchoolForSection
     *
     * .
     *
     */
    public function testGetSchoolForSection()
    {
    }

    /**
     * Test case for getSchools
     *
     * .
     *
     */
    public function testGetSchools()
    {
    }

    /**
     * Test case for getSchoolsForCourse
     *
     * .
     *
     */
    public function testGetSchoolsForCourse()
    {
    }

    /**
     * Test case for getSchoolsForTerm
     *
     * .
     *
     */
    public function testGetSchoolsForTerm()
    {
    }

    /**
     * Test case for getSchoolsForUser
     *
     * .
     *
     */
    public function testGetSchoolsForUser()
    {
    }

    /**
     * Test case for getSection
     *
     * .
     *
     */
    public function testGetSection()
    {
    }

    /**
     * Test case for getSections
     *
     * .
     *
     */
    public function testGetSections()
    {
    }

    /**
     * Test case for getSectionsForCourse
     *
     * .
     *
     */
    public function testGetSectionsForCourse()
    {
    }

    /**
     * Test case for getSectionsForResource
     *
     * .
     *
     */
    public function testGetSectionsForResource()
    {
    }

    /**
     * Test case for getSectionsForSchool
     *
     * .
     *
     */
    public function testGetSectionsForSchool()
    {
    }

    /**
     * Test case for getSectionsForTerm
     *
     * .
     *
     */
    public function testGetSectionsForTerm()
    {
    }

    /**
     * Test case for getSectionsForUser
     *
     * .
     *
     */
    public function testGetSectionsForUser()
    {
    }

    /**
     * Test case for getStudentsForUser
     *
     * .
     *
     */
    public function testGetStudentsForUser()
    {
    }

    /**
     * Test case for getTeachersForUser
     *
     * .
     *
     */
    public function testGetTeachersForUser()
    {
    }

    /**
     * Test case for getTerm
     *
     * .
     *
     */
    public function testGetTerm()
    {
    }

    /**
     * Test case for getTermForSection
     *
     * .
     *
     */
    public function testGetTermForSection()
    {
    }

    /**
     * Test case for getTerms
     *
     * .
     *
     */
    public function testGetTerms()
    {
    }

    /**
     * Test case for getTermsForSchool
     *
     * .
     *
     */
    public function testGetTermsForSchool()
    {
    }

    /**
     * Test case for getUser
     *
     * .
     *
     */
    public function testGetUser()
    {
    }

    /**
     * Test case for getUsers
     *
     * .
     *
     */
    public function testGetUsers()
    {
    }

    /**
     * Test case for getUsersForResource
     *
     * .
     *
     */
    public function testGetUsersForResource()
    {
    }

    /**
     * Test case for getUsersForSchool
     *
     * .
     *
     */
    public function testGetUsersForSchool()
    {
    }

    /**
     * Test case for getUsersForSection
     *
     * .
     *
     */
    public function testGetUsersForSection()
    {
    }
}
